### ISSUE TITLE
improving_documentation

### ISSUE THREAD

**Issue by Sachindrck** [Amit88k/The-Uplift-Project-DSA#13]
there are few typos in the documentation ([README.md](https://github.com/Amit88k/The-Uplift-Project-DSA/blob/master/README.md)) file guidelines section.

Ex: **Ckeck** instead of Check
Ex: **corrosponding** instead of corresponding

**Comment by Amit88k** [comment]
Thanks @Sachindrck for pointing this out. Fixed
